# ============================================================
#  Configuracion de conexion MySQL - API Generica
#  Edita este archivo para conectar con tu base de datos
# ============================================================

# Host donde corre MySQL (localhost o IP del servidor)
db.host=localhost

# Puerto de MySQL (por defecto 3306)
db.port=3306

# Usuario de MySQL
db.usuario=root

# Contrasena de MySQL (deja vacio si no tiene)
db.password=

# Nombre de la base de datos del SISTEMA (metadatos internos del ERP)
db.nombre_sistema=erp_sistema

# Nombre de la base de datos del CLIENTE (tablas del negocio)
db.nombre_cliente=erp_empresa

# Clave secreta para firmar los tokens JWT
app.secret_key=clave_secreta_de_prueba
